---
type: include
path: .reeve/build-step-image.yaml.tmpl
templateData:
  step: step-docker-build
  buildParams:
    DOCKER_VERSION: { var: DOCKER_VERSION }
    REEVE_TOOLS_VERSION: { var: REEVE_TOOLS_VERSION }
